AWSTemplateFormatVersion: '2010-09-09'
Description: 'Spotify OAuth Lambda Function and Related Resources'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']
  
  SpotifyClientId:
    Type: String
    NoEcho: true
    Description: 'Spotify Application Client ID'
  
  SpotifyClientSecret:
    Type: String
    NoEcho: true
    Description: 'Spotify Application Client Secret'
  
  SpotifyRedirectUri:
    Type: String
    Description: 'Spotify OAuth Redirect URI'

Resources:
  SpotifyOAuthFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${AWS::StackName}-spotify-oauth'
      Handler: index.handler
      Role: !GetAtt SpotifyOAuthFunctionRole.Arn
      Code:
        ZipFile: |
          // Lambda function code will be deployed separately
      Runtime: nodejs18.x
      Timeout: 30
      Environment:
        Variables:
          SPOTIFY_CLIENT_ID: !Ref SpotifyClientId
          SPOTIFY_CLIENT_SECRET: !Ref SpotifyClientSecret
          SPOTIFY_REDIRECT_URI: !Ref SpotifyRedirectUri
          DYNAMODB_TABLE: !Ref SpotifyTokensTable

  SpotifyOAuthFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt SpotifyTokensTable.Arn

  SpotifyTokensTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${AWS::StackName}-spotify-tokens'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

Outputs:
  SpotifyOAuthFunctionArn:
    Description: 'Spotify OAuth Lambda Function ARN'
    Value: !GetAtt SpotifyOAuthFunction.Arn
  
  SpotifyTokensTableName:
    Description: 'DynamoDB Table Name for Spotify Tokens'
    Value: !Ref SpotifyTokensTable
    