AWSTemplateFormatVersion: '2010-09-09'
Description: 'WAF rate limiting rule'

Resources:
  ApiRateLimitRule:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: api-rate-limit
      Description: Rate limiting for API endpoints
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      Rules:
        - Name: RateLimit
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 100
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: ApiRateLimit