AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Logging and Monitoring Setup for Streaming Analytics Platform'

Resources:
  # CloudWatch Log Group for Lambda Functions
  LambdaLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: '/aws/lambda/streaming-analytics'
      RetentionInDays: 30

  # CloudWatch Dashboard
  MainDashboard:
    Type: 'AWS::CloudWatch::Dashboard'
    Properties:
      DashboardName: 'streaming-analytics-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Invocations", "FunctionName", "streaming-analytics"],
                  [".", "Errors", ".", "."],
                  [".", "Duration", ".", "."]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Lambda Metrics"
              }
            },
            {
              "type": "metric",
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "streaming-analytics"],
                  [".", "ConsumedWriteCapacityUnits", ".", "."]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "DynamoDB Metrics"
              }
            }
          ]
        }

  # CloudWatch Alarms
  LambdaErrorAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: 'streaming-analytics-lambda-errors'
      AlarmDescription: 'Alert when Lambda function errors exceed threshold'
      MetricName: 'Errors'
      Namespace: 'AWS/Lambda'
      Dimensions:
        - Name: FunctionName
          Value: 'streaming-analytics'
      Statistic: 'Sum'
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: 'GreaterThanThreshold'
      TreatMissingData: 'notBreaching'

  DynamoDBThrottlingAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: 'streaming-analytics-dynamodb-throttling'
      AlarmDescription: 'Alert when DynamoDB requests are throttled'
      MetricName: 'ThrottledRequests'
      Namespace: 'AWS/DynamoDB'
      Dimensions:
        - Name: TableName
          Value: 'streaming-analytics'
      Statistic: 'Sum'
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: 'GreaterThanThreshold'
      TreatMissingData: 'notBreaching'

Outputs:
  LogGroupName:
    Description: 'CloudWatch Log Group Name'
    Value: !Ref LambdaLogGroup
  DashboardURL:
    Description: 'CloudWatch Dashboard URL'
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${MainDashboard}'