AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Raw Streaming Data DynamoDB table'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - 'dev'
      - 'staging'
      - 'prod'
    Description: 'Environment name for resource naming'

  ProjectName:
    Type: String
    Default: 'streaming-analytics'
    Description: 'Base name for the project resources'

Resources:
  RawStreamingDataTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-raw-streaming-data'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: source
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: source-timestamp-index
          KeySchema:
            - AttributeName: source
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  TableName:
    Description: 'Name of the DynamoDB table'
    Value: !Ref RawStreamingDataTable
  TableArn:
    Description: 'ARN of the DynamoDB table'
    Value: !GetAtt RawStreamingDataTable.Arn
  