// ... existing code ...

  HealthCheckMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref StreamingAnalyticsApi
      ResourceId: !Ref HealthCheckResource
      HttpMethod: GET
      AuthorizationType: API_KEY  # Changed from NONE to API_KEY
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: '{"status": "healthy"}'
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'
        - StatusCode: 429    # Add 429 Too Many Requests response
          ResponseModels:
            application/json: 'Empty'

  # Add API Key
  ApiKey:
    Type: 'AWS::ApiGateway::ApiKey'
    DependsOn: ApiDeployment
    Properties:
      Name: 'StreamingAnalyticsApiKey'
      Description: 'API Key for Streaming Analytics API'
      Enabled: true
      StageKeys:
        - RestApiId: !Ref StreamingAnalyticsApi
          StageName: !Ref StageName

  # Associate API Key with Usage Plan
  UsagePlanKey:
    Type: 'AWS::ApiGateway::UsagePlanKey'
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiGatewayUsagePlan

// ... existing code ...

Outputs:
  # Add these new outputs
  ApiKeyId:
    Description: 'API Key ID'
    Value: !Ref ApiKey
  
  ApiKeyValue:
    Description: 'API Key Value'
    Value: !GetAtt ApiKey.APIKeyId
    