AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for setting up AWS Glue workspace for Streaming Analytics Platform'

Resources:
  # S3 bucket for Glue scripts and temporary data
  GlueScriptsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-glue-scripts-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # IAM Role for Glue
  GlueServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt GlueScriptsBucket.Arn
                  - !Sub '${GlueScriptsBucket.Arn}/*'

  # Glue Database
  GlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${AWS::StackName}-streaming-analytics-db'
        Description: 'Database for Streaming Analytics Platform'

  # Glue Dev Endpoint
  GlueDevEndpoint:
    Type: 'AWS::Glue::DevEndpoint'
    Properties:
      EndpointName: !Sub '${AWS::StackName}-dev-endpoint'
      RoleArn: !GetAtt GlueServiceRole.Arn
      NumberOfNodes: 2
      GlueVersion: '3.0'
      Arguments:
        '--enable-glue-datacatalog': ''

Outputs:
  GlueScriptsBucketName:
    Description: Name of the S3 bucket for Glue scripts
    Value: !Ref GlueScriptsBucket
  
  GlueDatabaseName:
    Description: Name of the Glue database
    Value: !Ref GlueDatabase
    
  GlueDevEndpointName:
    Description: Name of the Glue development endpoint
    Value: !Ref GlueDevEndpoint
    
  GlueServiceRoleArn:
    Description: ARN of the Glue service role
    Value: !GetAtt GlueServiceRole.Arn
    